#!/bin/sh

# This script is experimental. Please understand it before you run it on
# your system. Just because Jeff borrowed it from Ingy and hacked it a
# bit, doesn't mean it will work for you.

if [ -e "/tmp/html" ]; then
    echo "Error: /tmp/html already exists. Perhaps remove it."
    exit 13
fi

# Create HTML slides.
slidez -i slidez.hbml -d slidez
# Move the html directory to /tmp
cp -r slidez /tmp || exit 1
# Stash any local stuff that isn't committed.
git stash || exit 1
# Switch to your gh-pages branch. (That you already created. Right?)
git checkout gh-pages || exit 1
# Remove all the files from the gh-pages branch.
rm -rf * || exit 1
# Move the slides in here.
mv /tmp/slidez/* . || exit 1
# Remove the slidez directory from /tmp
rmdir /tmp/slidez || exit 1
# Add any new files to git.
git add * || exit 1
# Commit your changes.
git commit -am 'Publish my slides' || exit 1
# Push them to GitHub.
git push origin gh-pages || exit 1
# Switch back to the master branch.
git checkout master || exit 1
# Get your uncommitted changes back.
git stash pop || exit 1

# Voilà! (hopefully)
